### ISSUE TITLE
more info on how to setup and run tests

### ISSUE THREAD

**Issue by newearthmartin** [ArcadeLabsInc/queenbee#5]
I'm trying to setup queenbee locally and I get an error for missing `BILLING_URL` and `SECRET_KEY`. 
Can you guys add more info on this and other configuration variables in the README?

Also can you add a section on how to test the service? both manually and how to run the tests

**Comment by newearthmartin** [comment]
Also, this in the README

```
poetry run uvicorn ai_spider:app --reload --log-config logging.conf
```

should be

```
poetry run uvicorn ai_spider:app --reload --log-config ../logging.conf
```

**Comment by newearthmartin** [comment]
Also this in the README

```
poetry run uvicorn ai_spider:app --reload --log-config logging.conf
```

should be 

```
poetry run uvicorn ai_spider:app --reload --log-config ../logging.conf
```

**Comment by earonesty** [comment]
that depends on where you run it from..... if you're in the root folder, the first one is correct

**Comment by earonesty** [comment]
see https://github.com/ArcadeLabsInc/queenbee/pull/16
